name: Publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.20.x
          cache: npm
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Check package types
        run: npm run check:package --if-present
      - name: Update version from release tag
        run: npm version from-git --no-git-tag-version
      - name: Publish to npm
        run: |
          version="$(node --print "require('./package.json').version")"
          if [[ "$version" = *-* ]]; then
            npm publish --tag next
          else
            npm publish
          fi
